### ISSUE TITLE
Search all code for typos 

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/testing-react-workshop#3]
One is tile instead of title

**Comment by NMinhNguyen** [comment]
One I know of is `tile` -> `title` on line 10 of `List.spec.js` in https://codesandbox.io/s/v3vnn457ol and line 15 of `List.spec.js` in https://codesandbox.io/s/jj3qm99n4v

**Comment by SaraVieira** [comment]
All fixed ! :D
